production:
  adapter: redis
  url: redis://redistogo:781ef13ea49b67784918d1f6ca4131ed@crestfish.redistogo.com:10579/

development:
  adapter: async
  url: redis://localhost:6379
test:
  adapter: async
